BaseUrl= "https://stefano.chiodino.uk"
LanguageCode= "en-GB"
Title= "Stefano Chiodino"
paginate = 5
DisqusShortname = "chiodino"
disqus_identifier = "chiodino"
Copyright = "All rights left - 2016"
canonifyurls = true
theme = "hugo-theme-bleak"

[params]
  description = "My personal website"
  cover = "images/cover.jpg"
  author = "Stefano Chiodino"
  authorlocation = "UK"
  # authorwebsite = "https://chiodino.uk"
  bio= "Web dev"
  logo = "/images/logo.png"
  googleAnalyticsUserID = "UA-77712099-1"
  ga = "UA-77712099-1"
  disqus = "chiodino"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feedly.com/i/subscription/feed/https://syui.github.io/atom.xml"
  githubName = "draga"
  twitterName = "ChiodinoStefano"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
